In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('winequality-red.csv')
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [4]:
X = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.20)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc = StandardScaler()

In [9]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [11]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [12]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix

In [15]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [16]:
l_c

array([[ 0,  0,  3,  0,  0,  0],
       [ 0,  1,  8,  6,  0,  0],
       [ 0,  0, 94, 33,  0,  0],
       [ 0,  0, 43, 82,  5,  0],
       [ 0,  0,  0, 32,  9,  0],
       [ 0,  0,  0,  2,  2,  0]], dtype=int64)

In [17]:
k_c

array([[ 0,  0,  3,  0,  0,  0],
       [ 0,  1,  8,  6,  0,  0],
       [ 0,  2, 84, 39,  2,  0],
       [ 0,  2, 33, 86,  9,  0],
       [ 0,  0,  7, 24, 10,  0],
       [ 0,  0,  1,  3,  0,  0]], dtype=int64)

In [18]:
d_c

array([[ 0,  0,  1,  2,  0,  0],
       [ 1,  0,  6,  7,  1,  0],
       [ 0,  5, 82, 36,  4,  0],
       [ 0,  0, 30, 83, 15,  2],
       [ 0,  0,  5, 13, 22,  1],
       [ 0,  0,  1,  2,  0,  1]], dtype=int64)

In [19]:
r_c

array([[ 0,  0,  3,  0,  0,  0],
       [ 1,  0,  8,  6,  0,  0],
       [ 0,  1, 99, 27,  0,  0],
       [ 0,  0, 28, 92, 10,  0],
       [ 0,  0,  3, 18, 20,  0],
       [ 0,  0,  0,  1,  2,  1]], dtype=int64)

In [20]:
s_c

array([[ 0,  0,  3,  0,  0,  0],
       [ 0,  0,  9,  6,  0,  0],
       [ 0,  0, 92, 35,  0,  0],
       [ 0,  0, 43, 87,  0,  0],
       [ 0,  0,  0, 41,  0,  0],
       [ 0,  0,  0,  4,  0,  0]], dtype=int64)

In [21]:
ks_c

array([[ 0,  0,  2,  1,  0,  0],
       [ 0,  0, 11,  4,  0,  0],
       [ 0,  0, 90, 37,  0,  0],
       [ 0,  0, 44, 81,  5,  0],
       [ 0,  0,  1, 28, 12,  0],
       [ 0,  0,  0,  3,  1,  0]], dtype=int64)

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [24]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.58125
KNN: 0.565625
Decision Tree: 0.5875
Random Forest: 0.6625
Linear SVC: 0.559375
Kernel SVC: 0.58125
